### ISSUE TITLE
Legend say that it heals -17 CLIENT_TRANSIENT_ERROR REQUEST_HASH_TOO_LONG

### ISSUE THREAD

**Issue by bphd** [lihenggui/blocker#1024]
Is it right? If so, how so exactly?

**Comment by lihenggui** [comment]
I don't understand your question. Please provide detailed context if you want to report issues.

**Comment by bphd** [comment]
Idk if I still experiencing the error, haven't checked logs, but by deactivating `persist.sys.pixelprops.gapps` `persist.sys.pixelprops.gms` properties and resintalling vending/gsf/gms and spoofing build and provider (and btw using that module, or Osm0sis one when that one bother me) I achieve device integrity. I have difficulties achieving strong integrity but it's probably because my CROM throw `UnsupportedOperationException()` when DroidGuard ask for certificate chain, have to figure out how to patch from MagiSK, or LSP, or by replacing files
