### ISSUE TITLE
[Bug]: blued极速版广告拦截不掉

### ISSUE THREAD

**Issue by MillionZBW** [lihenggui/blocker#1077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

把广告sdk全都禁用了，可是还是有广告
![Screenshot_2024-11-01-11-16-33-266_com danlan xiaolan-edit](https://github.com/user-attachments/assets/178f7d86-3789-4332-af81-f433937f6882)

**Comment by lihenggui** [comment]
Blocker不是广告拦截软件。请使用Adaway之类的替代
