### ISSUE TITLE
[FR]: Adaptive UI

### ISSUE THREAD

**Issue by lihenggui** [lihenggui/blocker#110]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the problem

Make application adapt to different screen sizes - compact, medium, large. 
The application should respond seamlessly when screen size changes. 

### Describe the solution

Example app: JetNews https://github.com/android/compose-samples/tree/main/JetNews
Medium article for adapting to different screen sizes: https://medium.com/androiddevelopers/jetnews-for-every-screen-4d8e7927752

**Comment by juliewww** [comment]
Fix in https://github.com/lihenggui/blocker/pull/520.
