### ISSUE TITLE
[FR]: 更新规则的地方能不能添加更新状态

### ISSUE THREAD

**Issue by polarxy** [lihenggui/blocker#1116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

更新规则的地方能不能添加更新状态

### Describe the solution

更新规则的地方能不能添加更新状态，不知道有没有更新成功，失败了能不能给个按钮手动点击更新

**Comment by lihenggui** [comment]
目前的更新策略是失败了会自动使用本地缓存，所以用户不需要特意关心规则更新的情况。本地缓存目前是最新的，不需要更新
