### ISSUE TITLE
导出完成的消息文本有误

### ISSUE THREAD

**Issue by yfdyh000** [lihenggui/blocker#13]
规则**导出**完成后，通知栏显示“xxx 已导入”。
[英文版](https://github.com/lihenggui/blocker/blob/ebb26ab221db37a1037b64926f1874d5d42dc3c3/app/src/main/res/values/strings.xml#L107) `%1$d jobs were done`是正确的，简中或繁中则是错误的`%1$d 已导入`、`%1$d 已匯入`。
建议拆分字符串，或者`xxx 项已完成`、`xxx 项处理完成。`之类的。

**Comment by lihenggui** [comment]
已知问题，准备着手解决

**Comment by lihenggui** [comment]
Done
