### ISSUE TITLE
[Documentation]: [README] IFW mode supports intent sender filter, which is mentioned not supported in README

### ISSUE THREAD

**Issue by fakerqu** [lihenggui/blocker#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Page URL (type "NEW" for a new page suggestion)

https://github.com/lihenggui/blocker/blob/main/README.zh-CN.md

### What's the documentation problem or suggestion?

Docs need improving!

According to android source code [cs.android.com](https://cs.android.com/android/platform/superproject/+/android-13.0.0_r31:frameworks/base/services/core/java/com/android/server/firewall/SenderPackageFilter.java), IFW supports 3 types of sender filter:

1. [Sender Filter](https://cs.android.com/android/platform/superproject/+/android-13.0.0_r31:frameworks/base/services/core/java/com/android/server/firewall/SenderFilter.java), which is used for filter intent send from system or filtered app
2. [Sender Package Filter](https://cs.android.com/android/platform/superproject/+/android-13.0.0_r31:frameworks/base/services/core/java/com/android/server/firewall/SenderPackageFilter.java), used for filter package name
3. [Sender Permission Filter](https://cs.android.com/android/platform/superproject/+/android-13.0.0_r31:frameworks/base/services/core/java/com/android/server/firewall/SenderPermissionFilter.java), used for filter packages which have provided permissions

**Comment by lihenggui** [comment]
Thank you. Let me check it and update the document. 
BTW There is a plan to rewrite the IFW module to support all fields the system provides. Stay tuned.

**Comment by lihenggui** [comment]
Updated by commit db21a1e and 1a9c45f.
