### ISSUE TITLE
[FR]: Multi-select Support

### ISSUE THREAD

**Issue by chr56** [lihenggui/blocker#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Multi-select of component Items currently are not supported for batch operations.

### Describe the solution

- Allow multi-select Component Items.
- Long click an item can trigger and enter multi-select mode, a toolbar would show, this item changes in look and appearance, and is added to selected items.
- Then simple click an another item can add it to selected items.
- The toolbar should have menu or action buttons to "block all of selected"  or "unblock all of selected"
- It would be better if this toolbar has action buttons to select all, or revert selection.
- It would be much better if it supports range selection (long click one item, long click another one, all of items in between are into selected)
- This toolbar has a navigation button with left-arrow icon to quit multi-select mode.

### Additional context

Version 2.0.1701

**Comment by juliewww** [comment]
Completed in https://github.com/lihenggui/blocker/pull/222

**Comment by lihenggui** [comment]
Design:
https://www.figma.com/file/T903MNmXtahDVf1yoOgXoI/Blocker?type=design&node-id=1-3&mode=design
![image](https://github.com/lihenggui/blocker/assets/5171312/4aa3a8e0-0242-4414-88b0-08941e47425b)

Credit to our designer: @COPtimer

**Comment by juliewww** [comment]
https://github.com/lihenggui/blocker/pull/300
