### ISSUE TITLE
[FR]: Jump to App Detail

### ISSUE THREAD

**Issue by chr56** [lihenggui/blocker#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

In Rule Detail of `Rules`, you can not jump to `App Detail` directly.

### Describe the solution

Allow jump to `App Detail` in Rule Detail of `Rules`.

This could be triggered by long click or icon click or just simply inside that 3-dots overflow menu.

### Additional context

Version 2.0.1701

**Comment by lihenggui** [comment]
Closed by https://github.com/lihenggui/blocker/pull/154
If you wanna try the latest version, you can join the beta tester 

```
Open the Play Store .
At the top right, tap the profile icon.
Tap Manage apps & devices. Installed.
Tap an app to open its detail page.
Under “Join the beta,” tap Join. Join.
```
