### ISSUE TITLE
阻止本页所有组件无效

### ISSUE THREAD

**Issue by ucxl** [lihenggui/blocker#155]
规则里阻止所有组件无效，只关闭第一个应用的，可能是有延时

**Comment by lihenggui** [comment]
@ucxl 在最新的版本不能复现这个情况，请问一下你用的版本是哪一个？

**Comment by ucxl** [comment]
最新版2.0.1705，三星s21u 安卓13，比如我在规则里点华为推送，然后点适用应用程序，进去点右上角菜单，阻止本页所有组件，执行完，只有前面几个应用有关闭，下面的有些还是打开状态

**Comment by lihenggui** [comment]
Fixed in https://github.com/lihenggui/blocker/pull/206/commits/30ddfeaf13907dd24260a07ca4ba3d3856887c9b

**Comment by lihenggui** [comment]
未来会重写ifw控制器模块以获得最佳性能
