### ISSUE TITLE
[FR]: Add new rules from exodus database

### ISSUE THREAD

**Issue by gab12** [lihenggui/blocker#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

The rules proposed in blocker are great, but they are not exhaustive.

### Describe the solution

Could we be more exhaustive on the identification of trackers by adding the trackers already known from the exodus database:
https://etip.exodus-privacy.eu.org/trackers/all?tracker_name=&trackers_select=exodus&approve_select=all&page=1

**Comment by lihenggui** [comment]
Cool, I am considering writing a batch to import these rules

**Comment by lihenggui** [comment]
Merged in https://github.com/lihenggui/blocker-general-rules/pull/5
