### ISSUE TITLE
[FR]: Move setting & support/feedback to menubar 

### ISSUE THREAD

**Issue by ThieuMinh26** [lihenggui/blocker#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Hi, i think its hard to access setting while menu bar or whatever it called have a lots of unused space . Can you move it somewhere else ?

### Describe the solution

I think it will be better if you move setting to there and support&feedback will be in setting

![Screenshot_2023-04-17-09-02-49-504-edit_com miui gallery](https://user-images.githubusercontent.com/92904701/232360831-bdba6aeb-feda-4869-8126-0c330f15c77b.jpg)

**Comment by COPtimer** [comment]
Hello, what actions in the Settings do you need to use frequently?

**Comment by lihenggui** [comment]
Which version of Android system are you using right now?
For the navigation issue, it is a known bug, and I will fix later.

**Comment by lihenggui** [comment]
I remembered that this issue has been resolved. Can you send a bugreport to
me if you encountered the reboot issue?

I assume you have a third party recovery installed. If random reboot
happens, you just need to delete all files in the `data/system/ifw` folder.

**Comment by COPtimer** [comment]
> I have bootloop when using intent firewall , so each time i reinstall this app i have to enable `controller type: pm ` , `dynamic color: on` , `show system apps/service info`
> 
> Also touching app list while im in settings doesnt move back to app list

These actions seem to be “one-time” operations, so we decided not to let the Settings occupy the valuable bottom bar space.

**Comment by lihenggui** [comment]
What's your device model?

**Comment by lihenggui** [comment]
> Xiaomi 2201117TG

I am also using Xiaomi. Could you upgrade to the latest MIUI 14? I didn't see any reboot issues.

**Comment by lihenggui** [comment]
If you don't like the pre-installed apps, you can use MIUI EU instead.

**Comment by lihenggui** [comment]
> > BTW the recommendation is that you don't block the system components unless you really know that it is safe to block.
> 
> If i use pm , its fine and bootloop doesnt happen
> 
> Btw what is this , running and disabled at same time ? ![Screenshot_2023-04-20-14-24-25-482-edit_com merxury blocker](https://user-images.githubusercontent.com/92904701/233291635-f7f008cd-c267-4511-81ad-7af0ebefd4db.jpg)

For system apps, I noticed this weird behavior. The app is disabled but the name is in the running list. You can just ignore it.

**Comment by lihenggui** [comment]
It is better to provide the system bugreport to me for further investigation. Or otherwise I can't fix this issue.

**Comment by COPtimer** [comment]
I think this issue can be closed (as won't fix), and a new issue should be created for the bug report.
