### ISSUE TITLE
[Bug]: 禁用组件后组件自启不显示

### ISSUE THREAD

**Issue by mpamxl** [lihenggui/blocker#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

当我禁用组件后，有些组件会随着软件启动被强行自启，MyAndroidTool会显示被启动的组件，但Blocker不会显示，依旧显示组件为禁用状态，请修复，并且可否像MAT一样将正在运行的组件高亮或者别的颜色显示？

**Comment by lihenggui** [comment]
请以blocker内置开关状态的为准。mat不支持检测blocker规则，pm组件状态是开启不代表组件可以正常被启动。（ifw可能同时生效）你可以用blocker的ifw控制器禁用一个MainActivity来查看效果。
预期效果是mat中这个组件是启用，但是你启动不了这个程序。

对于正在运行的服务，blocker有一个正在运行的标志。

**Comment by mpamxl** [comment]
我再看看，其次可否在规则匹配加入这样的功能，比如现在只能在规则下匹配软件，那能否在软件里匹配规则？比如我打开一个软件，里面除了接收器、服务等，主页加个规则页面，这样就可以更方便的把这个软件能匹配的规则禁用，而不是一个个在规则匹配里找

**Comment by lihenggui** [comment]
可以，有在考虑做这个功能。

**Comment by mpamxl** [comment]
但是我想着如果可以的话，还是和MAT同步，至少用PM规则的时候能同步，软件运行的时候确实也会自动启动部分禁用的规则，但Blocker就有些时候不会显示出来，这就感觉有点不如MAT完善，然后感觉Blocker自带的服务接收器好像也有点相对比较多几个，如果不是必要的话，可否考虑让Blocker更加"干净"好用，就可以完全取代MAT的感觉

**Comment by mpamxl** [comment]
在哪清空ifw规则呢？

**Comment by lihenggui** [comment]
设置里有清除ifw的选项

**Comment by lihenggui** [comment]
可以提供下是什么软件什么服务吗

**Comment by mpamxl** [comment]
我这边再测试下明天给你回复

**Comment by lihenggui** [comment]
@mpamxl 有更新吗

**Comment by cervy** [comment]
针对BroadcastReceiver组件可以像Myandroidtools那样显示出具体的action吗

**Comment by lihenggui** [comment]
可以

**Comment by lihenggui** [comment]
这个只是组件的pm状态被启用了，但是ifw状态不会发生改变，组件自身不会启动
请以blocker显示状态为准，如果你想要多个软件同步显示状态的话，建议切换到pm控制器上

**Comment by lihenggui** [comment]
正在运行的服务已经有运行标志了
