### ISSUE TITLE
[Bug]: 规则更新后重复问题

### ISSUE THREAD

**Issue by mpamxl** [lihenggui/blocker#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

今天更新了规则后，出现很多英文规则并且有很多重复，请修复。

**Comment by lihenggui** [comment]
能指出那些是重复的吗，我这边删除

**Comment by lihenggui** [comment]
Resolved in https://github.com/lihenggui/blocker-general-rules/pull/6/files
