### ISSUE TITLE
[Bug]: Android8 无法看清导航栏

### ISSUE THREAD

**Issue by Jesse205** [lihenggui/blocker#182]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [ ] I have searched StackOverflow

### What happened?

A bug happened!
![Screenshot_20230512-021538](https://github.com/lihenggui/blocker/assets/51242302/92356845-f0ff-4fbf-94f5-468ca0b7084b)

### Relevant logcat output

```shell
none
```

**Comment by lihenggui** [comment]
https://github.com/lihenggui/blocker/pull/194/commits/b0a9aeadd75441d081d2184059f31412734bf156
在此commit中修复

**Comment by Jesse205** [comment]
> https://github.com/lihenggui/blocker/pull/194/commits/b0a9aeadd75441d081d2184059f31412734bf156
> 在此commit中修复

我不懂这个项目，但是我感觉这样会出现另外的bug，比安卓8低的版本可能任然看不清

原因是谷歌从安卓8开始假如暗色导航栏图标的特性，安卓7及以下会始终为白色图标

* 安卓6以下：始终为白色状态栏图标
* 安卓6-安卓7：APP可以调节状态栏图标为黑色，但导航栏图标仍然为白色
* 安卓8-至今：APP可以调节状态栏与导航栏图标色

其中安卓8不支持在XML中定义导航栏图标颜色，但是在代码中可以，安卓8.1才开始支持在XML中定义导航栏图标色

**Comment by lihenggui** [comment]
![image](https://github.com/lihenggui/blocker/assets/5171312/ef703bcd-5f53-4500-9330-ad70eec0218f)
https://github.com/lihenggui/blocker/commit/290dbc2fdc4d6a8b3578f8bc6da65a5b67621a27
已修复
