### ISSUE TITLE
[help]小白请教: 

### ISSUE THREAD

**Issue by zhl111** [lihenggui/blocker#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

 我安装了这个app后，需要操作什么才能禁用各类组件？在默认的I F W模式下，我不管点击哪个都提示我无法关闭，因为我的手机没有root。所以我想知道，在这种啥也做不了的情况下，安装了这个app比不安装的实际功能是什么？感谢😂️

**Comment by lihenggui** [comment]
非专业用户请勿使用。
非root模式可以了解应用的组件信息和构成。

**Comment by lihenggui** [comment]
https://github.com/lihenggui/blocker/discussions
有问题可以来这里讨论，issue主要集中在应用问题上
