### ISSUE TITLE
[Bug]: 求助，好像禁用组件后不开机

### ISSUE THREAD

**Issue by mpamxl** [lihenggui/blocker#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

禁用Google组件后不开机好像，求怎么可以不开机的状态下恢复？

**Comment by lihenggui** [comment]
进入到recovery下删除`/data/system/ifw`目录下的所有文件即可

**Comment by lihenggui** [comment]
这个不是Blocker的程序问题，我先关闭了

**Comment by mpamxl** [comment]
问题我用的PM禁用呢？

**Comment by mpamxl** [comment]
现在还有个问题是rec下data是加密的状态

**Comment by lihenggui** [comment]
pm模式请删掉data/system/users/0/package_restrictions.xml

**Comment by lihenggui** [comment]
加密的话需要看一下怎么解密了
