### ISSUE TITLE
[FR]: CLI version for rooted user

### ISSUE THREAD

**Issue by xDoge26** [lihenggui/blocker#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

##### Describe the problem

I'm afraid this app will be like myandroidtools when no one maintains it anymore

##### Describe the solution

CLI version will be independent of android api levels

**Comment by lihenggui** [comment]
Can you describe more?

**Comment by lihenggui** [comment]
You mean a CLI tools that can control IFW, is that correct?

**Comment by lihenggui** [comment]
Previously I decided to make a flashable zip file to do the restoration. I
can consider to do that, but I recently I have limited time in the Blocker
project. Contribution welcomed.
