### ISSUE TITLE
[Bug]: Wrong color, language

### ISSUE THREAD

**Issue by xDoge26** [lihenggui/blocker#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Tested with lastest apk

![Screenshot_2023-07-08-19-02-09-931_com merxury blocker](https://github.com/lihenggui/blocker/assets/92904701/c4810d21-bcd1-412d-8769-0f0a81a6c22b)

**Comment by lihenggui** [comment]
Color is not correct. 
Blocker doesn't support Vietnamese language now.

**Comment by lihenggui** [comment]
Color issue fixed in commit : https://github.com/lihenggui/blocker/commit/024f543a54e3583223a1c7ea54542e157cc6e4d0
Introduce a new bug:  https://github.com/lihenggui/blocker/issues/218
