### ISSUE TITLE
[Bug]: Back button not working when the bottom sheet shows

### ISSUE THREAD

**Issue by lihenggui** [lihenggui/blocker#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Back button not working when the bottom sheet shows

**Comment by juliewww** [comment]
https://issuetracker.google.com/issues/278216859?pli=1

**Comment by juliewww** [comment]
It's fixed.
