### ISSUE TITLE
Your app on F-Droid?

### ISSUE THREAD

**Issue by ixearth** [lihenggui/blocker#22]
I have been using this app for a while and it's very useful.
thanks for making this great app and open source it!

blocks is a good alternative to MyAndroidTools which seems proprietary and outdated, I usually recommend others to use Blocker when I see them using MyAndroidTools. but some of them also don't prefer to download app from Play Store even this app does not contains GMS/GFS stuff.

can you make Blocker available on [F-Droid](https://f-droid.org/)?
seems Blocker is completely open source, the only problem could be the pre-build binary of Shizuku.
maybe consider build Shizuku from source, or create a build variant which build Shizuku stuff or just drop it in that variant?

[F-Droid  - FAQ - App Developers](https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included)

**Comment by lihenggui** [comment]
OK, I'll look into it.

**Comment by Poussinou** [comment]
I opened a Request For Packaging [here](https://gitlab.com/fdroid/rfp/issues/947).

**Comment by IzzySoft** [comment]
Our bot reported several issues (please follow Poussinou's link for details):

Fabric (most likely Crashlytics) must be removed. Those AARs as well, as we need to build the entire thing from source. So currently it seems not to fit our inclusion criteria.

For the AARs: you can either include the source with your repo (e.g. using submodules) – or point out where the source can be obtained, so we can build them from source.

Further, in your interest: please secure your gradlew as pointed out in the report :wink:

**Comment by ixearth** [comment]
seems Blocker is no longer available for download on playstore? unless the one downloaded it before.
Does google did this? @lihenggui maybe consider release apk on github? better to have this app on F-Droid tho, I think lots of F-Droid users would like this app.

**Comment by IzzySoft** [comment]
If it was Google removing it (I could imagine for violating their terms, as Blocker according to its description manipulates other apps) and not @lihenggui taking it down for some other reason: For a quick solution I could jump in and take it into [my repo](https://apt.izzysoft.de/fdroid) until it's ready for the official one. But then I'd need the APK – ideally attached to its resp. tag.

**Comment by Poussinou** [comment]
I still have access to this app (in France) @ixearth where are you from?

Otherwise use Aurora or something else then Google Play ;)

**Comment by ixearth** [comment]
oh sorry. forget what I said.
Blocker is still available on playstare seems nothing changed.

someone else said it seems removed it, and I tried to apply `&gl=<country_code>` at the end of playstore URL and checked it in Firefox private window. the "Install" button is grey out which made me think it's not available for users who does not installed it before.
but I just realized that the "Install" button will grey out when you set a `&gl=` to a different country. it does not grey out when I don't set to a different country. I tried on aurora store with default aurora account and I can install it.

however it's still good to have this app in IzzySoft's repo. maybe next version could include feature mentioned in #24 and release apk on github? then add to IzzySoft's repo, make a magisk module and may even bring it to Magisk repo.

**Comment by IzzySoft** [comment]
@lihenggui any news on the blobs? The RFP at F-Droid is still stalled because of them. If you can tackle that, please also consider establishing [Fastlane file structure](https://gitlab.com/snippets/1895688) for description, screenshots etc. Thanks!

**Comment by fabianski7** [comment]
up

**Comment by Poussinou** [comment]
@lihenggui Could you tag a new release so we can build this app at F-Droid, with maybe the Fastlane structure like Izzy asked?

**Comment by momobobe** [comment]
> @lihenggui Could you tag a new release so we can build this app at F-Droid, with maybe the Fastlane structure like Izzy asked?

It's tagged now, shall we begin? also @linsui

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11156 Could you please test the apk? The Fastlane is still missing.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11156 It will be available in 2-3 days.
