### ISSUE TITLE
[Bug]: Gitlab.com is not used if selected in Settings

### ISSUE THREAD

**Issue by licaon-kter** [lihenggui/blocker#250]
But... jihulab is :(

https://github.com/lihenggui/blocker/blob/7331367d7c578a37b0056bcf3a7678b25a3f19ea/core/network/src/main/java/com/merxury/blocker/core/network/model/OnlineSourceType.kt#L24

https://github.com/lihenggui/blocker/blob/7331367d7c578a37b0056bcf3a7678b25a3f19ea/core/model/src/main/java/com/merxury/blocker/core/model/preference/RuleServerProvider.kt#L24

**Comment by lihenggui** [comment]
Jihulab is the GitLab Chinese version. Because there will be issues connecting to GitHub in China, I created a mirror in JihuLab.

**Comment by licaon-kter** [comment]
Yes, but you can detect locale of the device/app and adjust accordingly `if not zh* then Gitlab`

**Comment by lihenggui** [comment]
Yes, I will fix it

**Comment by lihenggui** [comment]
Fixed in https://github.com/lihenggui/blocker/pull/251
