### ISSUE TITLE
Detection (?) & missing burger bar & force close when granting root after restoring it from back up

### ISSUE THREAD

**Issue by zputnyq** [lihenggui/blocker#26]
Hi, I was MyAndroidTools user, I decide to use this app since it's opensource.
I have a problem & confusion with the latest version from play store. When I see services section for e-mail app, EasTestAuthenticatorService shows on blocker as enabled by default while in myandroidtools it is disabled, idk which one is correct for this.

I also like to back up apps, sometimes using tb or directly copy apk file using explorer. I back up blocker at that time using tb, then uninstall it. However, when I restored it, the burger bar on upper left is gone, then after granting root permission, blocker force closed
I was testing it with xperia m4 stock 6.0.1 rooted with magisk 19.1
Thank you I really appreciate it

![_20190513_120706](https://user-images.githubusercontent.com/31039796/57597062-e7154680-7577-11e9-995d-2ab38c3ece23.JPG)
![_20190513_120758](https://user-images.githubusercontent.com/31039796/57597067-ef6d8180-7577-11e9-95ba-fb81b05c8619.JPG)

**Comment by lihenggui** [comment]
I'll check crash log in the play store console and reply you in detail later today.

**Comment by lihenggui** [comment]
Sorry, I cannot find your crash log in the play store console. I am going to use Crashlytics to upload these logs, and hope it will write down more useful information. My recommendation is to clean data manually for blocker if such crash happens.

Blocker use two ways to detect component status, one is Intent Filter, the other one is system status. If anyone detects the component is disabled, the switch toggle will be set to off. In theory, Blocker should be the correct one. 

Could you give me more information about this bug? Such as crash log (logcat) , the name of the email app. Is it AOSP email app or Gmail app?

**Comment by zputnyq** [comment]
Email app is stock (aosp).
Here's the logcat
[logcat.txt](https://github.com/lihenggui/blocker/files/3178422/logcat.txt)

**Comment by lihenggui** [comment]
Blocker updated
