### ISSUE TITLE
Shizuku模式无法使用

### ISSUE THREAD

**Issue by vidalouiswang** [lihenggui/blocker#27]
作者你好，非常感谢你的努力，我自己编译了apk安装到了手机里，因我使用三星手机，不想因为root而失去Samsung Pay等功能，所以使用Shizuku模式，但是使用Shizuku模式存在问题，我本人不会安卓开发，尝试修改无果，错误信息无法复制，我把截图发上来请看下，如可能，请尝试修复，谢谢。

![Screenshot0](https://user-images.githubusercontent.com/26226049/58500236-5152fb80-81b4-11e9-9c67-b1c660a64309.jpg)

**Comment by lihenggui** [comment]
看起来这个app不是test-only， 你在AndroidManifests.xml中添加了android:testOnly="true"了吗?

**Comment by vidalouiswang** [comment]
> 看起来这个app不是test-only， 你在AndroidManifests.xml中添加了android:testOnly="true"了吗?

**Comment by vidalouiswang** [comment]
> 看起来这个app不是test-only， 你在AndroidManifests.xml中添加了android:testOnly="true"了吗?

加上这个之后安装不上了，点了安装后会提示应用未安装，创建好了签名使用各种选项都试了一次，始终安装不上，能帮我打包一个吗？

**Comment by lihenggui** [comment]
> > 看起来这个app不是test-only， 你在AndroidManifests.xml中添加了android:testOnly="true"了吗?
> 
> 加上这个之后安装不上了，点了安装后会提示应用未安装，创建好了签名使用各种选项都试了一次，生成的APK始终安装不上，能帮我打包一个吗？

等我的电脑恢复了之后我会打一个包试一下

**Comment by vidalouiswang** [comment]
好的谢谢

lihenggui <notifications@github.com> 于 2019年6月4日周二 15:55写道：

**Comment by smoile** [comment]
修改过的apk能共享一下吗，我也是shizhuku模式下’

**Comment by NewBugger** [comment]
尽量不要考虑 shizuku 方案，自修 app 分分钟封号
