### ISSUE TITLE
Foss release vs Market release difference ?

### ISSUE THREAD

**Issue by xDoge26** [lihenggui/blocker#278]
Can you explain it ?

**Comment by lihenggui** [comment]
FOSS means this build will not use closed-source libraries like GMS and firebase.
The market version is the version that I published in the Play store and other markets like Coolapk. It contains GMS and firebase to collect user behaviors for product improvements.

You can check this build convention for knowing about the implementation: 
https://github.com/lihenggui/blocker/blob/main/build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt#L49
