### ISSUE TITLE
[Bug]: Bad UI experience in rules screen

### ISSUE THREAD

**Issue by lihenggui** [lihenggui/blocker#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Bad UI experience when users open the rule detail screen
After clicking any rules, the user will see a loading screen
![image](https://github.com/lihenggui/blocker/assets/5171312/cbd38593-2226-4f3d-8782-d0287c0ea096)
Then the frame
![image](https://github.com/lihenggui/blocker/assets/5171312/09f93d9f-51ed-4ba1-96ff-243ed228ec27)
Then the app list
![image](https://github.com/lihenggui/blocker/assets/5171312/bc5799ef-0398-42ac-a624-40fefbc76eb6)

Expected behavior:
When clicking the rule, the application will navigate to the rule detail screen, with the basic frame (with loading showing in the center of the list area)
![image](https://github.com/lihenggui/blocker/assets/5171312/f0c75777-1e2b-4b2b-8229-1f820b6ddca0)

After finishing loading, users can see the list on the screen.

**Comment by juliewww** [comment]
It should not be a bug.
It's rational to show a loading screen when getting ruleInfoUiState. Cannot show the topbar without ruleInfoUiState.info and ruleInfoUiState.appicon.

**Comment by juliewww** [comment]
Fixed in https://github.com/lihenggui/blocker/pull/300
