### ISSUE TITLE
关于组件详情界面的设计

### ISSUE THREAD

**Issue by 967018** [lihenggui/blocker#30]
您好，我从酷安得知您需要一些组件详情界面的设计灵感，在此向您推荐我的重设计方案，见下图。
这是一套良好适应手机与平板的设计方案，专注于向用户快速传达信息。
如果您只对组件详情界面的设计感兴趣，下图最左侧的平板就展示了组件详情界面。不过由于您给的草稿图信息太少我还不了解这个界面还有什么内容，所以这个设计并不完善，此处也只是雏形，但与重设计的界面有较高的契合度。
期待您的回复。

![宣传2](https://user-images.githubusercontent.com/8299251/59159469-7886c280-8afc-11e9-8168-cf76d553d25e.png)

**Comment by lihenggui** [comment]
十分感谢 我觉得这个设计很棒 准备按照这个设计进行开发 谢谢您提供创意

**Comment by 967018** [comment]
@lihenggui 
能和你进一步探讨这个设计吗？联系方式已经通过酷安私信发给你了。
