### ISSUE TITLE
[Bug]: Use package manager instead of intent firewall 

### ISSUE THREAD

**Issue by xDoge26** [lihenggui/blocker#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Use intent firewall to block "Google Play Service" services will cause bootloop on miui rom 

### Relevant logcat output

```shell
I dont wanna do that
```

**Comment by lihenggui** [comment]
You can switch to the PM controller in the settings.

**Comment by lihenggui** [comment]
Any updates @xDoge26 ?

**Comment by lihenggui** [comment]
It is a system issue, and blocker won't be aware of it. I will add rules
feature for the specific component in the future. Please check #308.
