### ISSUE TITLE
Blocker does not support modern Shizuku

### ISSUE THREAD

**Issue by tillcash** [lihenggui/blocker#33]
Legacy Shizuku has been deprecated since March 2019. Also, it won't run on Android 10 and above.

Please ask the developer of Blocker to update.

![shizuku-blocker-error](https://user-images.githubusercontent.com/19629778/78424996-fe2cbd80-768e-11ea-9c03-ab51a0c8bb93.png)

**Comment by NewBugger** [comment]
yes, Blocker remains a legacy shizuku api https://github.com/lihenggui/blocker/blob/81b6be4fd99112cf594b2e16a0127e5aaf95a383/core/src/main/java/com/merxury/blocker/core/shizuku/ShizukuController.kt#L11-L15  
i also don't how to use use new shizuku api..

**Comment by NewBugger** [comment]
i've almost complete the code worked with new Shizuku v3, will open later.

on Shizuku mode, you could do only two things:
- Enable or Disable the WHOLE application (regardingless of user or system app)
- you cannot control the application component enabled state unless your target is a TEST signed app (as Doc at this repo).

@lihenggui sorry what is the function BlockApplication and UnblockApplication within ManagerUtils?

**Comment by NewBugger** [comment]
and i've replaced outdated Rootshell to topjohnwu' Libsu, a modern library to call unix root method.

**Comment by NewBugger** [comment]
TEST wanted: first version of the new shizuku support https://github.com/NewBugger/blocker-Android/releases/tag/v0.0.4  
please aware that the frozen for application component (pm disable className) is not opened yet, it needs more test. and in mind that do not use IFW or PM methods that require your ROOT permission on your real phone. just help using Root mode on a emulator, it also needs more test.

**Comment by lihenggui** [comment]
@NewBugger Thank you for your efforts, please create an PR.

**Comment by lihenggui** [comment]
And I wonder if user really needs Shuzuku API or not since it could only control test-only applications. Is Magisk a better choice?

**Comment by NewBugger** [comment]
> And I wonder if user really needs Shuzuku API or not since it could only control test-only applications. Is Magisk a better choice?

none of them is good choice, the only one method called good could be use root permission for each once.

Shizuku is not reasonable for control component but frozen apps. so i've also  just prepared it to disable apps.

**Comment by lihenggui** [comment]
@NewBugger Could you please create a PR to branch `legacy`?

**Comment by NewBugger** [comment]
> @NewBugger Could you please create a PR to branch `legacy`?

i'm full open source with much changes. i''ll commit a pull if i have some time.

**Comment by NewBugger** [comment]
> TEST wanted:
> ~first version of the new shizuku support https://github.com/NewBugger/blocker-Android/releases/tag/v0.0.4~ https://github.com/NewBugger/blocker-Android/releases/tag/v0.0.7
> 
> aware that the frozen for application component (as `pm disable $className`) is not prepared yet, it depends on more troubles. ~and in mind that DO NOT use method that require your ROOT permission on your real phone. just help using Root mode on a emulator, it also needs more test.~ Root mode is almost available now, and use it as careful.

EDITED.

**Comment by NewBugger** [comment]
> i've almost complete the code worked with new Shizuku v3, will open later.
> 
> on Shizuku mode, you could do only two things:
> 
> * Enable or Disable the WHOLE application ~(user app only, currently not system app, need test)~ EDIT: _both_ user and system could be frozen.
> * you cannot control the application component enabled state unless your target is a TEST signed app (as Doc at this repo).
> 
> @lihenggui sorry what is the function BlockApplication and UnblockApplication within ManagerUtils?
> 
> EDIT: and i've also replaced outdated Rootshell to topjohnwu' Libsu, a modern library to call unix root conversion.

EDIT: this could be closed. https://github.com/lihenggui/blocker/issues/34

**Comment by lihenggui** [comment]
Done in branch legacy. Will publish a update to stores later
