### ISSUE TITLE
[Bug]: More action button will be covered in some small screen devices

### ISSUE THREAD

**Issue by lihenggui** [lihenggui/blocker#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

The more button will be covered by the search field in some small screen devices
But the blank area is still clickable. 

![image](https://github.com/lihenggui/blocker/assets/5171312/775487b7-335a-4fe8-b130-ced68b4d9895)

**Comment by juliewww** [comment]
Fixed in https://github.com/lihenggui/blocker/pull/334
