### ISSUE TITLE
[discussion] preparation for Shizuku api

### ISSUE THREAD

**Issue by NewBugger** [lihenggui/blocker#34]
[shizuku.zip](https://github.com/lihenggui/blocker/files/4679972/shizuku.zip)

i've had a fork, so i provide you a patch, based on your legacy branch. @lihenggui

**Comment by NewBugger** [comment]
this is only a provided-binder from Shizuku available, you cannot use any Blocker function with this only. cuz i don't know how to implement the requirement, refer: https://github.com/NewBugger/blocker-Android/commit/ebf21e856bc9960da59d071b74b9c7008101578e

**Comment by NewBugger** [comment]
addition: this patch is only for minSDK 28+ (maybe), you need implement a sdk check.

**Comment by lihenggui** [comment]
Merged to branch `legacy`, will do a self-test and publish it in this weekend.

**Comment by lihenggui** [comment]
> addition: this patch is only for min sdk 28+, which is support new Shizuku service for newer sdk, you need implement a sdk check for the older compatibility.

I decided to drop support for Android 4.4.

**Comment by NewBugger** [comment]
> > addition: this patch is only for min sdk 28+, which is support new Shizuku service for newer sdk, you need implement a sdk check for the older compatibility.
> 
> I decided to drop support for Android 4.4.

suggested for Android 6.0+ least.

**Comment by NewBugger** [comment]
> Merged to branch `legacy`, will do a self-test and publish it in this weekend.

then two weeks was gone :Lol.

**Comment by lihenggui** [comment]
@NewBugger I did rewrite the PR by myself in the last two weeks. Sorry for promised earlier, my job is quite busy so I don't have much time to maintain it. Thanks for your understanding.

**Comment by NewBugger** [comment]
> @NewBugger I did rewrite the PR by myself in the last two weeks. Sorry for promised earlier, my job is quite busy so I don't have much time to maintain it. Thanks for your understanding.

thanks for contribution, it is not a urge, but ask if there was commits i didn't find.

**Comment by lihenggui** [comment]
> > @NewBugger I did rewrite the PR by myself in the last two weeks. Sorry for promised earlier, my job is quite busy so I don't have much time to maintain it. Thanks for your understanding.
> 
> thanks for contribution, it is not a urge, but ask if there was commits i didn't find.

I didn't push changes to server side because I need to make sure everything works fine.

**Comment by NewBugger** [comment]
there is a latest Shizuku update:
>> * Support start via wireless adb (including adb over TLS from Android 11)  * Stop Shizuku from the menu  * Move start script to /data  * Change the icon for some reason  * Drop support for Android 5 and legacy Shizuku

**Comment by lihenggui** [comment]
Done, please check https://github.com/lihenggui/blocker/commit/5bb222af7db47f75070652484e7f856b46fcee7d

I will close this ticket once I published it into stores.

**Comment by NewBugger** [comment]
> Done, please check [5bb222a](https://github.com/lihenggui/blocker/commit/5bb222af7db47f75070652484e7f856b46fcee7d)
> 
> I will close this ticket once I published it into stores.

shizukuBinderWrapper cannot work if no concrete implementation. refer: https://github.com/RikkaApps/Shizuku/blob/7a237701d1aea6063b0b0c4d0f57227a6eafa2e5/sample/src/main/java/moe/shizuku/sample/SampleActivity.java#L155

**Comment by lihenggui** [comment]
@NewBugger Ok, I'll check again. Thanks.

**Comment by NewBugger** [comment]
though i don't know how to implement the interface for shizukuBinderWrapper (it is a abstract and empty interface) https://github.com/lihenggui/blocker/blob/5bb222af7db47f75070652484e7f856b46fcee7d/core/src/main/java/android/content/pm/IPackageManager.java#L29-L34

**Comment by NewBugger** [comment]
actually there is a alternative but not recommended method: https://github.com/NewBugger/blocker-Android/commit/099dedc2134212b74bb7083cc4946140326da891#diff-9c3eb173f3ad6c7da5fb0853ff8febdbL26

**Comment by NewBugger** [comment]
issue found: " system.err at" https://github.com/lihenggui/blocker/blob/5bb222af7db47f75070652484e7f856b46fcee7d/core/src/main/java/com/merxury/blocker/core/shizuku/ShizukuController.kt#L19  
i don't know how to find more error info.

**Comment by lihenggui** [comment]
> > Done, please check [5bb222a](https://github.com/lihenggui/blocker/commit/5bb222af7db47f75070652484e7f856b46fcee7d)
> > I will close this ticket once I published it into stores.
> 
> shizukuBinderWrapper cannot work if no concrete implementation. refer: https://github.com/RikkaApps/Shizuku/blob/7a237701d1aea6063b0b0c4d0f57227a6eafa2e5/sample/src/main/java/moe/shizuku/sample/SampleActivity.java#L155

I don't know why it can't work. In the official sample, `ShizukuSystemServerApi` is just a singleton class that holds `IPackageManager ` object. It is the same as what I did in `ShizukuContoller`.
https://github.com/lihenggui/blocker/blob/5bb222af7db47f75070652484e7f856b46fcee7d/core/src/main/java/com/merxury/blocker/core/shizuku/ShizukuController.kt#L19

**Comment by lihenggui** [comment]
> issue found: " system.err at"
> 
> https://github.com/lihenggui/blocker/blob/5bb222af7db47f75070652484e7f856b46fcee7d/core/src/main/java/com/merxury/blocker/core/shizuku/ShizukuController.kt#L19
> 
> 
> i don't know how to find more error info.

Do you have error stack?

**Comment by NewBugger** [comment]
@lihenggui the logcat message tells me only "System err: at IPackageManager.Stub.asInterface(source line number points to), at ... Presenter.kt".

have you test it yet?

**Comment by lihenggui** [comment]
> @lihenggui the logcat message tells me only "System err: at IPackageManager.Stub.asInterface(source line number points to), at ... Presenter.kt".
> 
> have you test it yet?

I tested in my Nexus 6 (Android 9 AOSP), it works fine. What's your device?

**Comment by NewBugger** [comment]
> > @lihenggui the logcat message tells me only "System err: at IPackageManager.Stub.asInterface(source line number points to), at ... Presenter.kt".
> > have you test it yet?
> 
> I tested in my Nexus 6 (Android 9 AOSP), it works fine in Shizuku mode for both ADB and root mode. The log output did not give me err info. What's your device?

Pixel 3a, android 10.  i'll test again

**Comment by lihenggui** [comment]
If there are errors, it is better to attach system log here.

**Comment by NewBugger** [comment]
> If there are errors, it is better to attach system log here.

how can i get more log info

**Comment by lihenggui** [comment]
> > If there are errors, it is better to attach system log here.
> 
> how can i get more log info

Connect your device to computer first, run command below

adb logcat > /replace/your/path/here.txt

**Comment by NewBugger** [comment]
> > > If there are errors, it is better to attach system log here.
> > 
> > how can i get more log info
> 
> Connect your device to computer first, run command below
> 
> adb logcat > /replace/your/path/here.txt
> 
> Then upload the log in this issue.

that is the logcat log, i view the logs and cannot find any other details, only nullpoint exception on That error.

**Comment by NewBugger** [comment]
could you share a release apk? i want to test it.

**Comment by lihenggui** [comment]
Are you always test the build in release mode? I saw there will throw `UnsupportedOperationException` in release apk. In debug it works fine, I should add some exception to R8.

**Comment by NewBugger** [comment]
i can get `pm = IPackageManager` on emulator (but cannot on my Pixel phone), then i met this on emulator:
```
W/System.err: java.lang.NoSuchMethodError: No interface method setApplicationEnabledSetting(Ljava/lang/String;III)V in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)  
  at io.github.newbugger.android.blocker.core.shizuku.api.ShizukuApi.setApplicationWrapper(ShizukuApi.kt:46)
```

**Comment by lihenggui** [comment]
> i can get `pm = IPackageManager` on emulator (but cannot on my Pixel phone), then i met this on emulator:
> 
> ```
> W/System.err: java.lang.NoSuchMethodError: No interface method setApplicationEnabledSetting(Ljava/lang/String;III)V in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)  
>   at io.github.newbugger.android.blocker.core.shizuku.api.ShizukuApi.setApplicationWrapper(ShizukuApi.kt:46)
> ```
> 
> of cource i had it interface wrote.

In my Android emulator (Android 10 ,QSR1.200403.001.6362371) it is working fine. It will show `Shell cannot change component state for xxx`. 
Have you tried the build in my branch?

**Comment by lihenggui** [comment]
Seems that you used wrong function signature. 
The actual one is `setComponentEnabledSetting(ComponentName componentName, int newState, int flags, int userId)`, refer to https://cs.android.com/android/platform/superproject/+/master:out/soong/.intermediates/frameworks/base/framework-minus-apex/android_common/xref28/srcjars.xref/frameworks/base/core/java/android/content/pm/IPackageManager.java;bpv=1;bpt=1;l=10544
But you used `void setApplicationEnabledSetting(String packageName, int newState, int flags, int userId)` which does not exist in `IPackageManager.java`

**Comment by NewBugger** [comment]
i found the reason for i cannot get the pm systemService: i cannot use proguard minify in release build, it resulted in this.

**Comment by NewBugger** [comment]
> Seems that you used wrong function signature.
> The actual one is `setComponentEnabledSetting(ComponentName componentName, int newState, int flags, int userId)`, refer to https://cs.android.com/android/platform/superproject/+/master:out/soong/.intermediates/frameworks/base/framework-minus-apex/android_common/xref28/srcjars.xref/frameworks/base/core/java/android/content/pm/IPackageManager.java;bpv=1;bpt=1;l=10544
> But you used `void setApplicationEnabledSetting(String packageName, int newState, int flags, int userId)` which does not exist in `IPackageManager.java`

indeed exists: https://cs.android.com/android/platform/superproject/+/master:out/soong/.intermediates/frameworks/base/framework-minus-apex/android_common/xref28/srcjars.xref/frameworks/base/core/java/android/content/pm/IPackageManager.java;bpv=1;bpt=1;l=10554

i'll test `setComponentEnabledSetting`

**Comment by NewBugger** [comment]
oops:) i miss a variable `java.lang.String callingPackage`, i will figure it again.

**Comment by NewBugger** [comment]
the last one:

>> i cannot get the pm system service if use proguard/R8 minifyEnabled (in release build for real phone).

a proguard rule correction is needed..

**Comment by lihenggui** [comment]
Done, check https://github.com/lihenggui/blocker/commit/0bf7d5d9b9d24169650b6596361d00713d8d35fd

**Comment by NewBugger** [comment]
my proguard rule (from forked) warns me an error "unsolved class" on such as `-keep class android.os.** { *; }`, if change to `-keep class android.os.* { *; }` then no error.

**Comment by lihenggui** [comment]
> my proguard rule (from forked) warns me an error "unresolved class name" on such as `-keep class android.os.** { *; }`, if change to `-keep class android.os.* { *; }` then no error.
> 
> android studio 4.0.0, gradle 4.0.0/6.1.1
> 
> EDIT: https://stackoverflow.com/questions/62080165/unresolved-class-name-proguard-rules-android-studio-4-0

Seems that it is a bug in Android Studio, I will suppress it temporally.

**Comment by NewBugger** [comment]
>> but android studio 4.0 still said it's unresolved. I think it should be bug instead of fix by suppress it.

> my proguard rule (from forked) warns me an error "unresolved class name" on such as `-keep class android.os.** { *; }`, if change to `-keep class android.os.* { *; }` then no error.
> 
> android studio 4.0.0, gradle 4.0.0/6.1.1
> 
> EDIT: https://stackoverflow.com/questions/62080165/unresolved-class-name-proguard-rules-android-studio-4-0
