### ISSUE TITLE
Provide prebuilt apk

### ISSUE THREAD

**Issue by proletarius101** [lihenggui/blocker#36]
I notice that this repo doesn't provide prebuilt apks on GitHub. The last build was updated in 2018. Probably it's because the new version is not ready. 

For those who are interested in the lastest code, I write a CI script and you may download apks here: https://gitlab.com/secure-system/blocker/-/pipelines

**Comment by NewBugger** [comment]
(not necessary cuz:) the 2018 build is enough, while the latest code is NOT prepared for distributions, even you cannot build it.

**Comment by lihenggui** [comment]
@proletarius101 Thanks, I will check
