### ISSUE TITLE
[Bug]: Matching indicator is too long in the rules card

### ISSUE THREAD

**Issue by lihenggui** [lihenggui/blocker#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Try to restrain the indicator's width to a maximum of 25% of the total width.
![image](https://github.com/lihenggui/blocker/assets/5171312/af159dd8-092c-4dbf-b1c5-44ca5666ea00)

**Comment by juliewww** [comment]
Fix in https://github.com/lihenggui/blocker/pull/370
