### ISSUE TITLE
[FR]: Add the loading indicator in the rules screen

### ISSUE THREAD

**Issue by lihenggui** [lihenggui/blocker#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

When the user enters the rules screen, the app will read the rules, matching the apps one by one. It is slow, and there is no loading indicator to tell users about this behavior.

### Describe the solution

Add a loading indicator in the toolbar, next to the 'Rules' title. It will show the progress of the current state. For example, there are 200 rules in the app, and we are in the number of 50, so it will show a (50/200) indicator on the screen to tell users that the application is waiting to update the list content. 

When the application finishes loading, the app should hide the indicator.

**Comment by juliewww** [comment]
completed in https://github.com/lihenggui/blocker/pull/394
