### ISSUE TITLE
[Bug]: No default icon in the rule detail

### ISSUE THREAD

**Issue by lihenggui** [lihenggui/blocker#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

![image](https://github.com/lihenggui/blocker/assets/5171312/6e658bef-97bb-48c8-82bd-5ba2706fef6d)
1. No default icon in the rule detail screen
2. The rule detail won't be able to show the rule with a long name.

**Comment by juliewww** [comment]
Fix in https://github.com/lihenggui/blocker/pull/372
