### ISSUE TITLE
Feature request: Greenify prescription-like ruleset

### ISSUE THREAD

**Issue by ghost** [lihenggui/blocker#37]
Add a new kind of ruleset that:
- Auto apply to new installed apps.
- Block components in all apps in one line of rule.

Optional, but it will be better if these feature get added in this app:
- Download and generate rules fron exodus privacy.
- Compatable with Greenify's prescription rule format.

**Comment by NewBugger** [comment]
- tip 1 is more likely to provide such filter pattern, doing the similiar as Rikka AppOps
- tip 4 is what i wanted yet, doing at it, and time needed

**Comment by lihenggui** [comment]
IFW supports wildcards. In theory we can do this.

**Comment by NewBugger** [comment]
> IFW supports wildcards. In theory we can do this.

automatic works at IFW is really dangerous then not recommended.

**Comment by NewBugger** [comment]
> * tip 1 is more likely to provide such filter pattern, doing the similiar as Rikka AppOps. not much meanings but available.
> * tip 4 is what i wanted yet, doing at it, and time needed

EDIT: i'm not interested and discontinued now. you can find some initial parts in https://github.com/NewBugger/blocker-Android/commit/acdfe78c3062587f252b3b980c2af72cee47a027

**Comment by lihenggui** [comment]
This feature is in the main branch now.
