### ISSUE TITLE
does this work on Android 11 without root? and a couple of other questions

### ISSUE THREAD

**Issue by jawz101** [lihenggui/blocker#40]
Running Android 11 beta on a Pixel 3a

I tried Blocker with Shizuku Manager and every time I toggled any receivers, activies, services, or content providers I would get an error thrown.

My other question is - If it does work, will I have to run the Shizuku Manager adb script every time I reboot my device?

**Comment by NewBugger** [comment]
Shizuku mode would work only when app you toggled has manifested `android:text`, says it is a debug level app.

Yes.

**Comment by lihenggui** [comment]
If your device does not have root permission, you need to modify the apk first, set a property (test only=true), then install on the device. After doing this you could control the components by using Suzuku. 
Next question is yes, Shizuku lose its permission if you reboot your device. If you want to make some changes you need to gain permission again. But the component state will be saved once you made changes.
