### ISSUE TITLE
[FR]: 能否加入刷新功能

### ISSUE THREAD

**Issue by zqisme** [lihenggui/blocker#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

打开blocker后，有其他应用程序运行或服务发生变化时，blocker无法实时反映，只能强制关闭再启动才会显示有新的应用在运行。

### Describe the solution

加入一个强制刷新的功能

**Comment by juliewww** [comment]
Complete in https://github.com/lihenggui/blocker/pull/434
