### ISSUE TITLE
[FR]: Focus on the search bar automatically when clicking the search button

### ISSUE THREAD

**Issue by lihenggui** [lihenggui/blocker#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

In order to make the keyboard show automatically.

### Describe the solution

 Focus on the search bar automatically when clicking the search button

**Comment by juliewww** [comment]
Fix in https://github.com/lihenggui/blocker/pull/425

**Comment by lihenggui** [comment]
Fix in https://github.com/lihenggui/blocker/commit/00ee8639de7436f438a6683e306964a02b5fc326
