### ISSUE TITLE
about newer storage

### ISSUE THREAD

**Issue by NewBugger** [lihenggui/blocker#42]
EDIT:

for if Android 11 and target api 30

concluded 4:
- do not use `requestLegacyStorage`, as it is deprecated on target 30, it is for up to target 29
- do not use `File` access api, as for api 29=+ scoped storage
- ~~SAF is considerable, but MediaStore is on my preferred~~ `MediaStore` available on api 30=+ (due to Android 10 problems), then api 29 uses `SAF`
- use /externalstorage/Download/Blocker as output folder, not /externalstorage/Blocker/

~~i'm working on modern storage practices https://github.com/NewBugger/blocker-Android/commit/fbff816 , it more test needed~~ done. available on even Android 11

about `Storage Permission`:
- MediaStore: do not need any storage permission (unless the user uninstall (or reinstall) blocker app)
- SAF: choose one directory for one time to grant permission
- traditional File Api: do not mind, throw it out

https://developer.android.com/training/data-storage/shared/media#media-location-permission

**Comment by NewBugger** [comment]
done. test welcome. rule files is now on Download/Blocker path.

**Comment by NewBugger** [comment]
edited. pull request will be sent long later, because codes is too much to clean up and merge to this channel.

**Comment by NewBugger** [comment]
finally i recommended to use SAF for storage implementation.

then much problems occurs:

 - (almost none) compatibility issue on varies of Android version
 - (if persistable usage (we actually need this) ) worse performance
 - uri values need be saved ourselves, SharedPreferences simply works for this
 - user's manually operation (from ActionOpenDocument Intent), we need to tell user how to choose "Blocker" folder and confirm it (it is: grant uri permission)
 - root path /externalstorage/Blocker cannot be used on Android 11, use /externalstorage/Download/Blocker instead

wait for your comment.

**Comment by lihenggui** [comment]
I think it's done now. 
But I haven't tested these cases on 4.4 devices. The code should be running without any issues above 5.0
