### ISSUE TITLE
Block services on RAM.

### ISSUE THREAD

**Issue by UniverseCodex01** [lihenggui/blocker#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

On devices with 4gb of RAM and lower, when system is running out of memory, the battery optimization can kills unimportant system UI services, like wallpaper services, this generates a very usual black screen  by few seconds on home return, I need an option to block services on RAM to avoid system kills them when it's running out of memory, I know that exists tools to completely block app on ram but this method it's unstable with System UI.

### Describe the solution

Add an option to block apps services on RAM to avoid battery optimization kills them when system is running out of memory.

### Additional context

Not additional context.

**Comment by lihenggui** [comment]
I don't quite understand your request. Are you asking if you'd like to use Blocker to prevent a particular service from being terminated?

**Comment by UniverseCodex01** [comment]
> I don't quite understand your request. Are you asking if you'd like to use Blocker to prevent a particular service from being terminated?

EXACTLY IT! It's possible?

**Comment by lihenggui** [comment]
> > I don't quite understand your request. Are you asking if you'd like to use Blocker to prevent a particular service from being terminated?
> 
> EXACTLY IT! It's possible?

Sorry, Blocker did not provide this feature for now. I believe memory management is done by LMK (Low Memory Killer) of Android.
If you have root permission you can follow this tutorial to control the logic by yourself. 
https://android.stackexchange.com/questions/183401/is-there-a-way-with-root-to-prevent-android-task-killer-from-killing-certain



Blocker can add this feature, but it is not a high priority for me. I will focus on completing the online rules and hosts features first before working on this improvement.

**Comment by lihenggui** [comment]
https://github.com/OneB1ank/A1Memory
@UniverseCodex01 I think you can try this tool

**Comment by UniverseCodex01** [comment]
> https://github.com/OneB1ank/A1Memory
> @UniverseCodex01 I think you can try this tool

Thanks it works 👍
