### ISSUE TITLE
[Bug]: Rules do not download

### ISSUE THREAD

**Issue by muchuelo** [lihenggui/blocker#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Rules will not download. There's just a spinning wheel. I see a connection to jihulab.com, but no connections either to Gitlab or GitHub (I've tried both).

I'm on Android 9 and Blocker 2.0.2942

Two versions back, the rules downloaded no problem, but this version and the previous one both fail to download rules.

**Comment by lihenggui** [comment]
Can you share the screenshot or relevant logs?

**Comment by muchuelo** [comment]
Here's a screenshot. 

Can you remind me how to do the logcat thing, please. It's a while since I did that.

Then I will try clearing the data and re-initialize the app and report back.

**Comment by lihenggui** [comment]
I solved this issue before, and it shouldn't happen in the latest version. It is fine to clear data now, I don't wanna waste your time to find logs. I'll implement writing logs to the storage soon.

**Comment by muchuelo** [comment]
So I cleared the data and re-initialized the app. Then set Rules language to Simplified Chinese, source GitHub, and all I'm seeing is the spinning wheel. No download. 

And I'm still only seeing a connectiin to jihulab.com

**Comment by muchuelo** [comment]
Uninstalled and reinstalled. Now there's no connection to jihulab.com but neither is there one to GitHub. Same spinning wheel.

**Comment by lihenggui** [comment]
It is odd because GitHub should work. AFAIK my GitLab account was suspended due to traffic issues : (

**Comment by lihenggui** [comment]
> I've noticed the same issue, too. Download source doesn't seem to matter (GitHub won't download either), I'm running on the latest app version 2.0.3058 from Fdroid; clearing cache and app data didn't help.

Will check on this issue.
