### ISSUE TITLE
[Bug]: GUI language setting does not work

### ISSUE THREAD

**Issue by muchuelo** [lihenggui/blocker#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Android 9
Blocker 2.0.2942

My phone is not set to English. That's not a problem for me. Neither is it a problem for me that most apps automatically install themselves in the phone's default language. (What **does** completely baffle me is why it is so rare for app developers to consider the possibility that a user might want to change the language of the interfsce in their **multilingual** app! But that does not apply here - you guys actually provide a language option - both for the interface and the rules, so well done for that!)

However, just occasionally I prefer to have an app interface in English, so I tried to change Blocker to English and it just doesn't work.

By the way, when the Rules **were** downloading (in a previous version) the "Rules in English" setting **did** work.

So, looks like a bug to me.

**Comment by lihenggui** [comment]
Hi @muchuelo This app supports [per app language settings](https://developer.android.com/guide/topics/resources/app-languages) if you are using Android 13+. But you are using Android 9, so the application language will follow the system settings.

I attempted to implement a language setting in the application, but the result was unsatisfactory as it caused the application interface to flash and reload. If you believe it would be beneficial, I can consider reintroducing this feature. 
https://github.com/lihenggui/blocker/blob/main/feature/settings/src/main/kotlin/com/merxury/blocker/feature/settings/item/BlockerSettings.kt#L70C12-L70C12


I've implemented a language switch within the application to select the rules language. The issue you mentioned arises from the absence of an English translation for the current general rules.
https://github.com/lihenggui/blocker-general-rules/tree/main/zh-cn

If I have the time, I'll work on providing an English translation. It's important to note that the rules language settings apply to the component descriptions, not the ones you are currently viewing.

**Comment by muchuelo** [comment]
RE: https://github.com/lihenggui/blocker/blob/main/feature/settings/src/main/kotlin/com/merxury/blocker/feature/settings/item/BlockerSettings.kt#L70C12-L70C12

Well. if I'm reading the code right, it looks like native Chineses, Russian and English speakers might like that feature.

RE: GitHub rules are only in Chinese ... I would be willing to help with translation to English, but ONLY if I can use DeepL, NOT Google.

DeepL translations are far superior to those from Google, and they profess a commitment to privacy (something which is anathema to Google!) But DeepL only has a "Chinese" option - it doesn't say whether that is Traditional or Simplified. Maybe it handles both the same.

**Comment by lihenggui** [comment]
> RE: https://github.com/lihenggui/blocker/blob/main/feature/settings/src/main/kotlin/com/merxury/blocker/feature/settings/item/BlockerSettings.kt#L70C12-L70C12
> 
> Well. if I'm reading the code right, it looks like native Chinese, Russian and English speakers might like that feature.
Blocker currently supports five languages: English, Simplified Chinese, Traditional Chinese, Russian, and Spanish. If I want to display this option in the settings, I will need to update the selections in the settings.
I have not provided translations for other languages; in such cases, it should default to English if unsupported.


> RE: GitHub rules are only in Chinese ... I would be willing to help with translation to English, but ONLY if I can use DeepL, NOT Google.
> 
> DeepL translations are far superior to those from Google, and they profess a commitment to privacy (something which is anathema to Google!) But DeepL only has a "Chinese" option - it doesn't say whether that is Traditional or Simplified. Maybe it handles both the same.

Contributions are greatly appreciated. The default option of 'Chinese' is fine; I believe the translation tool will handle it well.

**Comment by muchuelo** [comment]
So I've got the general.json file. Now to try and  get my RegEx hat on and extract the Chinese lines for translation...
