### ISSUE TITLE
[Bug]: Selection state is not correct

### ISSUE THREAD

**Issue by lihenggui** [lihenggui/blocker#527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Please check the video, the first time the selection works normally, but the second time the selection breaks. The UI state won't reflect the actual selection status, and the count of the apps is not correct. 

https://github.com/lihenggui/blocker/assets/5171312/da78dc7c-1ac9-4465-9d10-82baeec83440

**Comment by lihenggui** [comment]
> 3314版本仍然存在该问题，当清空所有ifw规则后，清除软件数据重新进入后，从规则里全部禁用组件后退出软件重开后规则里的开关部分仍是打开状态，已检查ifw目录下配置文件内容是正确的。并且保留ifw后清除软件数据重新打开后所有开关都是启用状态，再次禁用后概率失败或者出现其他异常，比如所有活动被禁止了（之前突然打不开对应软件以为是系统问题，后来排查到是被全部关闭了，只能手动删掉ifw目录下的配置，然而开关却显示启用状态

这个应该是缓存没有更新导致的
https://github.com/lihenggui/blocker/pull/572
会在这里修复，马上并入开发分支

**Comment by lihenggui** [comment]
> > > 3314版本仍然存在该问题，当清空所有ifw规则后，清除软件数据重新进入后，从规则里全部禁用组件后退出软件重开后规则里的开关部分仍是打开状态，已检查ifw目录下配置文件内容是正确的。并且保留ifw后清除软件数据重新打开后所有开关都是启用状态，再次禁用后概率失败或者出现其他异常，比如所有活动被禁止了（之前突然打不开对应软件以为是系统问题，后来排查到是被全部关闭了，只能手动删掉ifw目录下的配置，然而开关却显示启用状态
> > 
> > 
> > 这个应该是缓存没有更新导致的 #572 会在这里修复，马上并入开发分支 Bug: #569
> 
> 使用 #569 你提供的这个包测试后发现内容提供者所有项无法被关闭

有错误提示吗
可否开一个新的issue，这个问题和#527无关

**Comment by juliewww** [comment]
Cannot reproduce.
