### ISSUE TITLE
建议加入对应用程序的各项 服务、广播接收器、活动和内容提供者 的注释功能

### ISSUE THREAD

**Issue by MSGOOHPA** [lihenggui/blocker#54]
因为某些应用程序的各项 服务、广播接收器、活动和内容提供者 的命名有点令人难以理解，或者乍一眼看上去不知道其用途，所以希望加入自行对应用程序的各项 服务、广播接收器、活动和内容提供者 进行注释的功能，让用户可以更加方便地调教应用程序。不需要内置这些注释，因为这可能会引起某些争议或带来某些麻烦，仅提供 添加、编辑、导入、导出 注释的功能即可。

**Comment by lihenggui** [comment]
正在进行中

**Comment by lihenggui** [comment]
Closed by https://github.com/lihenggui/blocker/pull/409
