### ISSUE TITLE
Importing rules doesn't work

### ISSUE THREAD

**Issue by HarriBuh** [lihenggui/blocker#569]
I recently exported both ifw and regular rules of an app and after a while tried importing these rules back to revert changes. But besides a popup telling me about the ongoing process, ~~nothing happened or changed. The values remain at their CHANGED, not UNchanged state.~~
**I had to manually quit and clear Blocker's cache before the reverted values became visible again.**

**Comment by lihenggui** [comment]
@HarriBuh 
https://github.com/lihenggui/blocker/suites/18888094779/artifacts/1102864478

You can try this build to check if this issue has been fixed or not.
