### ISSUE TITLE
[Bug]: 使用提供的包测试后发现内容提供者所有项无法被关闭

### ISSUE THREAD

**Issue by fecent** [lihenggui/blocker#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

使用 #569 提供的包测试后发现内容提供者所有项无法被关闭，其他分类就可以正常开关，没有提示任何错误，就是关了开关后自动打开了。另外开关识别不到位的问题应该得以解决，未测试导入导出规则是否正常

### Relevant logcat output

https://github.com/lihenggui/blocker/assets/29230064/427cb4ad-f6e9-45ba-aab3-ac67b6c1e0a9

**Comment by lihenggui** [comment]
请问可以提供一下应用程序日志吗
在程序主界面更多选项菜单->支持和反馈 -> 导出错误日志

**Comment by lihenggui** [comment]
2023-12-09T06:02:21.365Z D/LocalComponentRepository$controlComponent: Control com.xiaomi.market/com.xiaomi.market.provider.LazyFileProvider to state false
2023-12-09T06:02:21.368Z D/RootApiController: Switch component: com.xiaomi.market/com.xiaomi.market.provider.LazyFileProvider, state: 2

看起来是RootApi有问题，但是它没有抛出异常。我需要点时间调查这个问题

**Comment by lihenggui** [comment]
> Screenrecorder-2023-12-13-19-29-24-518.mp4 
> [Blocker-log-2023-12-13T11-30-14-894Z.zip](https://github.com/lihenggui/blocker/files/13660170/Blocker-log-2023-12-13T11-30-14-894Z.zip)
> 
> @lihenggui 大佬，刚刚在酷安更新最新了，好像还是不行啊，而且bug更多了

应该是显示有问题 你下次进来就好了
这是下个版本需要解决的问题，看起来列表更新逻辑出了点问题，刷新的是缓存值里面的页面
