### ISSUE TITLE
关于高级搜索

### ISSUE THREAD

**Issue by baimo2333** [lihenggui/blocker#59]
首先我是安卓12MIUI13Blocker1.1.53的用户。
第一，图标与酷安的不同？虽然这和高级搜索没有什么关系，即使点击搜索栏的❌。
![IMG_20220319_034308](https://user-images.githubusercontent.com/45843580/159073165-dc81a4ee-cb4e-40db-87e8-3911f71fedca.jpg)
第二，当搜索框空白时会展示所有服务，当我输入再删除后。
![Screenshot_2022-03-19-03-19-28-765_com merxury blocker](https://user-images.githubusercontent.com/45843580/159073355-94055d1b-2cce-4c40-b3da-0913169f5b2d.jpg)
第三，高级搜索的开关似乎没用，当在高级搜索里改变开关后，在应用程序列表里并没有变化，重新加载高级搜索后该开关却是变成初始的状态。反过来，在应用程序列表里改变开关状态，高级搜索里就正常显示，同时发现一个问题如下。
第四，当加载高级搜索列表后，再在应用程序列表里改变开关状态，高级搜索开关状态并未改变，但只要重新加载就发现是改变了的。
综上所述，高级搜索是否暂时只是一个摆设，或者是该死的MIUI13搞得鬼。
另外，大佬加油！

**Comment by lihenggui** [comment]
1. Blocker的图标一直没变过，这应该是MIUI根据自己的风格动态对图标进行了调整
2. 这个是特意做的功能，不过有几位用户当成bug反馈了，后面考虑移除
3. 有一位小米root的用户反馈了类似的问题，我准备着手调查。我手上几台magisk root的机子是正常使用的
4. 高级搜索列表不会根据组件状态动态刷新，因为监听这个状态比较麻烦/也不是很必要。目前就麻烦手动多刷新一次吧，精力需要放在更值得做的功能上 （比如在线规则） :)

**Comment by dhdkrystal** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lihenggui** [comment]
新版已修复完毕
