### ISSUE TITLE
[Bug]: Service running stay at 0 

### ISSUE THREAD

**Issue by xDoge26** [lihenggui/blocker#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

A bug happened!
![Screenshot_2023-12-30-11-30-39-999_com merxury blocker](https://github.com/lihenggui/blocker/assets/92904701/c9972db8-81ee-4f8e-8b4c-5044cae2c284)

**Comment by lihenggui** [comment]
Actually I didn't write code to fix this issue :(
It was caused by fetching the running service data before initializing the controller
