### ISSUE TITLE
[求助]点开APP导入规则失败,高级搜索里线上规则404

### ISSUE THREAD

**Issue by shinji-ikari** [lihenggui/blocker#63]
感谢开发的软件,感觉还是挺有意思的,虽然还是没怎么搞懂应该怎么用才好.

手机一加5T, blocker版本最新版的测试版1.2.55-alpha

备份设置里有设置保存目录,

点开程序之后 到处规则没问题, 导入规则直接提示失败,请检查是否获得了权限. 
导出导入IFW规则没问题.
点了一下应用信息查看权限,是写着:未请求任何权限.

然后就是 高级搜索--线上规则 net work call has failed for a following reason: 404 not found. 在线规则源从gitee跟github都不行.
这个功能还没正式开放?

现在就碰上了这两个问题,求个解.

**Comment by dhdkrystal** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lihenggui** [comment]
我最近没有设备进行开发，我会在能进行开发的时候优先查看这个问题

**Comment by lihenggui** [comment]
Hi @shinji-ikari 请问现在的版本还有这个问题吗

**Comment by shinji-ikari** [comment]
抱歉,现在才看到回应,问题本身在更新到了新版本之后并没有碰上了.感谢维护与更新. 再次抱歉现在才想起这个问题与提醒.
(。・＿・。)ﾉI’m sorry~
