### ISSUE TITLE
rule description page can not be copied and the link can not be clicked

### ISSUE THREAD

**Issue by him007** [lihenggui/blocker#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

The text on the rule description page can not be copied and the link can not be clicked,Not convenient.

规则描述上的页面文字无法复制、链接无法点击，不方便。

### Describe the solution

text Replicable
link Clickable
文字可复制
链接可点击

**Comment by lihenggui** [comment]
I planned to use some markdown renderer to show the description contents.
