### ISSUE TITLE
[QUESTION] No more FOSS releases?

### ISSUE THREAD

**Issue by HarriBuh** [lihenggui/blocker#658]
Just as the title says: The FOSS version of your brilliant app is now 2 versions behind the MARKET version, with no sign of a change to this.

**Comment by lihenggui** [comment]
Because people keep asking what's the difference between the foss version
and the market version. So I just keep one version in the release page.
I can revert this change.

**Comment by lihenggui** [comment]
> So what IS the difference then? 😅

Please check: 
https://github.com/lihenggui/blocker/pull/756/files
