### ISSUE TITLE
[Bug]: Importing MyAndroidTools rules broken

### ISSUE THREAD

**Issue by tethergate** [lihenggui/blocker#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

The option to import MyAndroidTools rules has stopped working in recent FOSS releases.

Blocker v2.0.3058 (FOSS) is the last version where the option still works.

I choose the option "Import MyAndroidTools Rules" under "Settings" and after selecting a rules file to import I expect a notification to popup showing the progress of the import but nothing happens.

**Comment by lihenggui** [comment]
The problem for me is that I cannot install MAT on my emulator anymore, so I cannot test it
