### ISSUE TITLE
[FR]: Sort by running service

### ISSUE THREAD

**Issue by xDoge26** [lihenggui/blocker#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

![Screenshot_2024-03-02-14-30-05-857_com merxury blocker](https://github.com/lihenggui/blocker/assets/92904701/2708ab02-1485-4e3b-b9ab-532c0886144a)

### Describe the solution

It would be nice if we have priority : running first as miui have no way to check a running service

**Comment by lihenggui** [comment]
In design, the running service should be placed on the top.
https://github.com/lihenggui/blocker/blob/main/core/domain/src/main/kotlin/com/merxury/blocker/core/domain/components/SearchComponentsUseCase.kt#L126
