### ISSUE TITLE
Blocker的UI有一些问题 There are some problems with the Blocker UI

### ISSUE THREAD

**Issue by Jesse205** [lihenggui/blocker#74]
![Uploading Screenshot_20220921-042118.jpg…]()

在安卓8.0（EMUI8.0）上，导航栏背景为黑色，状态栏为白色，在安卓10（HarmonyOS2.0）上，导航栏为灰色，状态栏正常
但是从安卓8.0开始，导航栏支持亮色模式，应该使用背景颜色，或者ActionBar颜色。在安卓8，已经支持状态栏亮色模式。
正常情况：
![Screenshot_20220921-042139](https://user-images.githubusercontent.com/51242302/191358451-8f602a91-f526-4c21-a27f-57a4a318d639.jpg)

**Comment by dhdkrystal** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Jesse205** [comment]
抱歉，图片上传畅玩
我共上传了两张图片，刚才那张是对比图。第二张图片上传错误，无法上传
[![Snipaste-2022-11-06-11-44-51.png](https://i.postimg.cc/BbVZp2nb/Snipaste-2022-11-06-11-44-51.png)](https://postimg.cc/7JSyYG7r)

**Comment by lihenggui** [comment]
更新一下 新的UI正在制作中，做完之后这个问题就可以解决

**Comment by lihenggui** [comment]
问题已顺带修复 https://github.com/lihenggui/blocker/pull/119
会随着新版本发布
