### ISSUE TITLE
[Bug]: Unable to reset Intent Firewall Rules

### ISSUE THREAD

**Issue by x-0D** [lihenggui/blocker#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

While i play around with Blocker, i applied some destructive rules to system. But there's no way to reset rules / restore starting point state. Also, most of bulk operations in search not working

**Comment by lihenggui** [comment]
Hi @x-0D Seems that the reset function works, but due to cache issues, it doesn't update in time. You can relaunch the app to see changes.

**Comment by lihenggui** [comment]
Hi @x-0D Please check this version
https://github.com/lihenggui/blocker/releases/tag/v2.0.4044
