### ISSUE TITLE
[FR]: 个人觉得UI交互不够简洁，一些建议以供参考

### ISSUE THREAD

**Issue by seeyou-github** [lihenggui/blocker#782]
一，规则列表太长，信息太多
      建议：
                  1，可以关闭SDK列表中到 组件名称
                  2，匹配0个应用SDK 可以不显示
                  3，SDK列表上面增加：一键禁用所有app+显示禁用数量      

======================缺陷===================================
每次app更新了，安装了新app，都需要一次次到去设置
基于此：提出二 三建议。

二，增加基于SDK的规则
                例如：将某些广告SDK加入 此列表，那么所有app只要集成了这些SDK都会被禁用

         触发时机：监听app安装事件
                           打开Blocker触发
                           用户手动触发 

         优点： 安装新app后无须一个个配置 

三，增加基于关键字的规则
        可以自定义关键字，比如xxxAD,xxxPush，只要组件名称符合就禁用

【针对二 三，可以增加个白名单功能，个别app可能禁用会出错】

**Comment by lihenggui** [comment]
https://github.com/lihenggui/blocker/issues/77
https://github.com/lihenggui/blocker/issues/341

**Comment by lihenggui** [comment]
可以关闭SDK列表中到 组件名称
这个是什么意思

**Comment by lihenggui** [comment]
> 匹配0个应用SDK 可以不显示
https://github.com/lihenggui/blocker/pull/784

**Comment by lihenggui** [comment]
> > 可以关闭SDK列表中到 组件名称 这个是什么意思
> 
> ----->关闭SDK列表中【的】 组件名称
> 
> 规则Tab中，SDK列表会显示组件名称如：com.huawei.hms.anytics 一大串组件名称
> 
> 列表太长不简洁

@COPtimer 这个看一下？

**Comment by COPtimer** [comment]
关于第一条建议各小项：
1. 不予采纳。列表需要组件简称的首字母向用户提示序列位置。针对文本长度的问题，我记得之前有实现在组件列表中使用密集型字体（Roboto Condensed），但我在Android 14的AVD上测试却没有生效？ @lihenggui 
2. 采纳。功能实现见#784。
3. 采纳。需要将“选择多项”功能覆盖至“SDK”面板。

**Comment by lihenggui** [comment]
> 1. 我记得[之前有实现](https://t.me/blockerandroid/17128)在组件列表中使用密集型字体（Roboto Condensed），但我在Android 14的AVD上测试却没有生效？ @lihenggui

这个很早就实现了 并且没有修改过

**Comment by lihenggui** [comment]
> 关于第一条建议各小项：
> 
> 1. 不予采纳。列表需要组件简称的首字母向用户提示序列位置。针对文本长度的问题，我记得[之前有实现](https://t.me/blockerandroid/17128)在组件列表中使用密集型字体（Roboto Condensed），但我在Android 14的AVD上测试却没有生效？ @lihenggui

修复在 https://github.com/lihenggui/blocker/pull/796

**Comment by COPtimer** [comment]
关于第一条建议的第一小项，我之前没搞懂你的意思。目前设计稿已作出调整，将在未来实装到Blocker上。
