### ISSUE TITLE
[建议] 建议使用 ifw 为默认模式

### ISSUE THREAD

**Issue by hosxy** [lihenggui/blocker#8]
使用ifw禁用的组件是无法复活的，效果比类似MAT的方法的效果要好很多，所以请开发者考虑一下能否将ifw作为默认禁用模式。

**Comment by lihenggui** [comment]
ifw控制器目前在小米部分手机有问题，修复这些问题之后会设置成默认

**Comment by lihenggui** [comment]
问题已修复，下个版本中设置
