### ISSUE TITLE
建议增加功能，选择导出规则为应用名，导出规则时可以手动重命名

### ISSUE THREAD

**Issue by rkdawn** [lihenggui/blocker#805]
有时候会反复验证一个App规则对App的影响，于是会产生多个备份，所以这个重命名感觉很有必要，恳求开发者考虑一下，谢谢。

**Comment by lihenggui** [comment]
导入要怎么处理

**Comment by rkdawn** [comment]
> 导入要怎么处理

不太明白，导入不是和现在这样一样吗

**Comment by lihenggui** [comment]
需要考虑如果有多个规则，应用要选择哪个导入。批量导入的情况下，手工选择会中断进程。

**Comment by rkdawn** [comment]
> 需要考虑如果有多个规则，应用要选择哪个导入。批量导入的情况下，手工选择会中断进程。

明白你的意思了，Blocker的规则是针对应用单独输出的，所以会出来每个不同的应用配置文件，统一导入的话，规则会没法判定导入哪一个
感觉可以借鉴一下写轮眼的输出方式，所有的输出配置可以写在一个文件内，单独单独导出的是另外一个配置。

**Comment by lihenggui** [comment]
> > 需要考虑如果有多个规则，应用要选择哪个导入。批量导入的情况下，手工选择会中断进程。
> 
> 明白你的意思了，Blocker的规则是针对应用单独输出的，所以会出来每个不同的应用配置文件，统一导入的话，规则会没法判定导入哪一个 感觉可以借鉴一下写轮眼的输出方式，所有的输出配置可以写在一个文件内，单独单独导出的是另外一个配置。

这样批量备份的共享就不方便了，看起来这个改动会引入其他更多的问题

**Comment by lihenggui** [comment]
目前来说修改导入导出逻辑会引起更多的问题，考虑到开发成本和用户收益，这个提议暂时不会被采纳。如果有更好的解决方式我们可以在discussion里讨论。
