### ISSUE TITLE
无法获取权限，应用可能无法正常工作

### ISSUE THREAD

**Issue by GordonYoungCao** [lihenggui/blocker#937]
手机使用的sui模式（kernelsu sui模块），应用卸载后，重新打开就会提示这个错误，切换到其它模式也会提示这个错误
![Screenshot_20240727-211929_Blocker](https://github.com/user-attachments/assets/5a8f01a6-cf00-4927-a332-cb48813f285f)

**Comment by GordonYoungCao** [comment]
从sui模式切换到pm模式和IFW模式都会跳出这个提示，反过来切换到sui模式不会提示，但依旧不能正常工作
![Uploading Screenshot_20240727-225404_USB摄像头.png…]()

**Comment by GordonYoungCao** [comment]
从sui模式切换到pm模式和IFW模式都会跳出这个提示，反过来切换到sui模式不会提示，但依旧不能正常工作
![Screenshot_20240727-225404_USB摄像头](https://github.com/user-attachments/assets/f3d6ce9f-87f0-4ea9-b757-f66c905df4dd)
![Screenshot_2024-07-27-22-49-18-930_com merxury blocker](https://github.com/user-attachments/assets/e2852f1e-8246-4f90-a717-02d18176ed8e)
![Screenshot_2024-07-27-22-49-21-897_com merxury blocker](https://github.com/user-attachments/assets/933de6e9-94f2-4b08-a0eb-cbda5291f994)

**Comment by lihenggui** [comment]
可以提供一下应用程序日志吗
在主界面右上角，反馈与支持，发送调试日志处

**Comment by lihenggui** [comment]
权限是正常的，只是hint显示错误了
已修复 https://github.com/lihenggui/blocker/pull/1002
