### ISSUE TITLE
[Bug]: The app doesn't seem to do anything

### ISSUE THREAD

**Issue by stepanzak** [lihenggui/blocker#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

A bug happened!
Well... not exactly a bug.
I don't know if I just didn't get what the app is supposed to do, but I thought it will block google ads.
I gave it root privileges in KernelSU and allowed it access to Sui. I blocked all of Google Ads components, but still the apps show google ads as always. I tried switching between Intent Firewall, Package Manager and Sui, but nothing seems to work. It turns off the components, but I can't tell if something has changed or not.

**Comment by lihenggui** [comment]
Blocker is not an ad-blocker (at least for now it is not). It is supposed to enable/disable some unnecessary components for Android applications. For example, I don't want the application to receive the boot complete broadcast so I can disable the receiver to prevent the application from booting itself.
Usually, advertisements are not strongly binded to components, so you'll see the advertisement will not disappear. It is recommended to use some professional ad-blocker apps to block ads.
https://github.com/AdAway/AdAway

BTW, I am also trying to implement the engine to block ads, but it requires time to finish. 
https://github.com/lihenggui/blocker/issues/406
