### ISSUE TITLE
[BUG] SUI implementation (still) buggy

### ISSUE THREAD

**Issue by HarriBuh** [lihenggui/blocker#992]
I decided to use Blocker again after some time, and it seems like there is still that bug that led me to change to another app ops app back then:

Blocker doesn't recognise a properly installed and working SUI and will always give out an error message.
See screenshot for reference.
It DOES work somehow after just ignoring the message, but it doesn't seem to work properly - I always cross-check with App Manager (another app that is capable of editing app ops in A14, [https://github.com/MuntashirAkon/AppManager](url)
), where none of the changes done in Blocker are shown, whereas the other way around will always work.

![obscura1726046697413.jpg](https://github.com/user-attachments/assets/4da7d80f-6997-4203-a7e5-8e70edc4dfea)

![Screenshot_20240911-112901.png](https://github.com/user-attachments/assets/60d0f3da-6919-42ef-87e5-a86507b36c2a)

Google Pixel 7
Android 14
Root, Magisk 27007
Blocker app version 2.0.4803 FOSS

**Comment by lihenggui** [comment]
It is an expected behavior since AppManager did not recognize Blocker IFW rules, vice versa it is the same. If you switch to the PackageManager controller, the component status can be synced since both apps are using the same API to detect and control component status.

**Comment by lihenggui** [comment]
> And, returning to the main issue of my ticket: Why doesn't SUI work as intended/ why is there an error message if anything was fine?  

There should be bugs in the sui implementation, and Sui is not the mode I frequently use. You are the first one to report this issue to me. I planned to check this issue on the code side, but I need to spend some time on this.

**Comment by lihenggui** [comment]
> But you are aware that App Manager blocks both with IFW AND root, right?

I know, but I have never used App Manager. The IFW rules are supposed to be different. Blocker uses the app's package name as the file name. I am not sure how App Manager did this, but it should be different.

> As I said, Blocker DOES recognise changes made with App Manager.

If App Manager uses `PackageManager.setComponentEnabledSetting` API, Blocker can recognize changes made by App Manager.
