### ISSUE TITLE
[FR]: Add "disabled" count on "SDK/Tracker" page

### ISSUE THREAD

**Issue by nkh0472** [lihenggui/blocker#993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Currently, the "SDK/Tracker" page only displays the count of active services. After disabling several unnecessary SDK services some time ago, newly installed or updated applications may inadvertently introduce new, unwanted services that are enabled. Without a clear indication of the number of "disabled" services on the "SDK/Tracker" page, it is difficult to quickly identify which new services have been enabled and require attention.

### Describe the solution

To address this issue, I propose adding a "disabled" count next to the existing service count on the "SDK/Tracker" page. This will allow users to easily see which services need to be reviewed and potentially disabled, improving the overall manageability of the SDK services.

**Comment by lihenggui** [comment]
@COPtimer  I have one concern, if we add the 'disable' count, we have to put a text label under the number, making the UI narrow and complex. What do you think about this?

**Comment by nkh0472** [comment]
> @COPtimer I have one concern, if we add the 'disable' count, we have to put a text label under the number, making the UI narrow and complex. What do you think about this?

Just for ref, MyAndroidtools has such kind of layout.
![image](https://github.com/user-attachments/assets/6ed9a5b6-f9b8-4aff-a87b-732fb7442ecc)

**Comment by lihenggui** [comment]
In the Blocker app, we show the number of applications that contain this SDK. It is hard to show how many applications actually disabled the entire SDK. For example, you disabled one component under the Firebase service, how can I present this case on the screen?
Would you happen to have any suggestions about it?

**Comment by lihenggui** [comment]
Or it could be better to present the number of blocked services in the rule detail screen.
![image](https://github.com/user-attachments/assets/659ce057-a007-48a3-8ee8-e0bc796378a7)

**Comment by lihenggui** [comment]
ping @nkh0472

**Comment by nkh0472** [comment]
> Or it could be better to present the number of blocked services in the rule detail screen.

That makes sense :)
